site_name: Michael Colletti 
site_author: Michael Colletti 
copyright: ScreenDream Productions 2023
remote_name: me
site_description: For code, learning resources, cool tools and projects
repo_url: https://github.com/michaelcolletti/me.git
repo_name: Code and Things

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - json
        - python
    locale: en
#    custom_dir: custom
    nav_style: dark
#    color_scheme: 
#    static_templates:
#        - sitemap.html
    include_sidebar: true
nav:
  - Home: index.md
  - Bass: bass.md
  - DevOps: devops.md
  - GCP: gcp.md
  - About: about.md
  - K8s: k8s.md

#    - 'index.md'
#    - 'about.md'
#    - 'devops.md'
#    - 'k8s.md'
