site_name: Michael Colletti 
site_url: https://github.com/michaelcolletti/me.git
site_author: Michael Colletti 
copyright: Creative Possibilities Inc. 2024
remote_name: 
site_description: For code, learning resources, cool tools and projects
repo_url: https://github.com/michaelcolletti/me/
repo_name: Code and Things
edit_uri: 'blob/main/docs/'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - json
        - python
    locale: en
#    custom_dir: custom
    nav_style: dark
#    color_scheme: 
#    static_templates:
#        - sitemap.html
    include_sidebar: true
nav:
  - Home: index.md
  - Upwork: 'https://www.upwork.com/freelancers/~01543c426937f19998?mp_source=share'
  - Bass: bass.md
  - DevOps: devops.md
  - DevOps-GenAI Primer: genai-devops-primer.md
  - Backstage: backstage.md
  - Resume: resume.md
  - Markdown Resume: pretty-resume.md
  - GCP: gcp.md
  - Terraform: terraform.md
  - k8s research Part 1: k8s-history-architecture.md
  - k8s research Part 2: k8s-devops.md
